# Generated by Django 4.2.16 on 2024-10-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitescrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='house_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
