# Generated by Django 4.2.8 on 2024-09-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_auth_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginhistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="auth_provider",
        ),
        migrations.RemoveField(
            model_name="user",
            name="creation_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="customization_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="download_count",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tier",
        ),
        migrations.DeleteModel(
            name="GoogleToken",
        ),
        migrations.DeleteModel(
            name="LoginHistory",
        ),
        migrations.DeleteModel(
            name="UserTier",
        ),
    ]
